//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EncWAVtoAC3.rc
//
#define IDR_MAINFRAME                   101
#define IDD_DIALOG_MAIN                 102
#define IDD_DIALOG_ENGINES              103
#define IDD_DIALOG_MUX                  104
#define IDD_DIALOG_WORK                 105
#define IDD_DIALOG_ABOUT                106
#define IDR_MENU_MAIN                   107
#define IDR_MENU_LIST                   108
#define IDR_ACCELERATOR_MAIN_MENU       109
#define IDC_STATIC_QUALITY              1001
#define IDC_STATIC_BITRATE              1002
#define IDC_CHECK_VBR                   1003
#define IDC_SLIDER_BITRATE              1004
#define IDC_LIST_SETTINGS               1005
#define IDC_BUTTON_PRESETS_DEFAULTS     1006
#define IDC_COMBO_PRESETS               1007
#define IDC_BUTTON_PRESET_ADD           1008
#define IDC_BUTTON_PRESET_DEL           1009
#define IDC_STATIC_SIMD                 1020
#define IDC_CHECK_SIMD_MMX              1021
#define IDC_CHECK_SIMD_SSE              1022
#define IDC_CHECK_SIMD_SSE2             1023
#define IDC_CHECK_SIMD_SSE3             1024
#define IDC_STATIC_SAMPLE_FORMAT        1030
#define IDC_COMBO_RAW_SAMPLE_FORMAT     1031
#define IDC_STATIC_SAMPLE_RATE          1032
#define IDC_EDIT_RAW_SAMPLE_RATE        1033
#define IDC_SPIN_RAW_SAMPLE_RATE        1034
#define IDC_STATIC_CHANNELS             1035
#define IDC_EDIT_RAW_CHANNELS           1036
#define IDC_SPIN_RAW_CHANNELS           1037
#define IDC_STATIC_ENGINE               1040
#define IDC_COMBO_ENGINES               1041
#define IDC_STATIC_THREADS              1050
#define IDC_EDIT_THREADS                1051
#define IDC_SPIN_THREADS                1052
#define IDC_LIST_FILES                  1060
#define IDC_BUTTON_ADD                  1070
#define IDC_STATIC_OUTPUT               1071
#define IDC_EDIT_OUTPUT_PATH            1072
#define IDC_BUTTON_BROWSE               1073
#define IDC_BUTTON_ENCODE               1074
#define IDC_CHECK_MULTIPLE_MONO_INPUT   1075
#define IDC_BUTTON_MUX_WIZARD           1076
#define IDC_BUTTON_ENGINES              1077
#define IDC_STATIC_OPTION_VALUE         1078
#define IDC_COMBO_SETTING               1079
#define IDC_STATIC_PRESET               1080
#define IDC_STATIC_IN_00                1090
#define IDC_STATIC_IN_INFO_00           1091
#define IDC_STATIC_IN_01                1092
#define IDC_STATIC_IN_INFO_01           1093
#define IDC_STATIC_IN_02                1094
#define IDC_STATIC_IN_INFO_02           1095
#define IDC_STATIC_IN_03                1096
#define IDC_STATIC_IN_INFO_03           1097
#define IDC_STATIC_IN_04                1098
#define IDC_STATIC_IN_INFO_04           1099
#define IDC_STATIC_IN_05                1100
#define IDC_STATIC_IN_INFO_05           1101
#define IDC_STATIC_OUT                  1102
#define IDC_STATIC_OUT_INFO             1103
#define IDC_PROGRESS_CURRENT            1104
#define IDC_STATIC_ELAPSED_CURRENT      1105
#define IDC_PROGRESS_TOTAL              1106
#define IDC_STATIC_ELAPSED_TOTAL        1107
#define IDC_STATIC_GROUP_ENCODING       1108
#define IDC_BUTTON_FL                   1120
#define IDC_BUTTON_FR                   1121
#define IDC_BUTTON_FC                   1122
#define IDC_BUTTON_LFE                  1123
#define IDC_BUTTON_SL                   1124
#define IDC_BUTTON_SR                   1125
#define IDC_BUTTON_S                    1126
#define IDC_BUTTON_IMPORT               1130
#define IDC_BUTTON_EXPORT               1131
#define IDC_BUTTON_CLEAR_FL             1140
#define IDC_BUTTON_CLEAR_FR             1141
#define IDC_BUTTON_CLEAR_FC             1142
#define IDC_BUTTON_CLEAR_LFE            1143
#define IDC_BUTTON_CLEAR_SL             1144
#define IDC_BUTTON_CLEAR_SR             1145
#define IDC_STATIC_LABEL_FL             1150
#define IDC_STATIC_LABEL_FR             1151
#define IDC_STATIC_LABEL_FC             1152
#define IDC_STATIC_LABEL_LFE            1153
#define IDC_STATIC_LABEL_SL             1154
#define IDC_STATIC_LABEL_SR             1155
#define IDC_STATIC_FILES                1160
#define IDC_COMBO_CHANNEL_CONFIG        1161
#define IDC_CHECK_CHANNEL_CONFIG_LFE    1162
#define IDC_STATIC_TEXT_CHANNEL_CONFIG  1163
#define IDC_EDIT_FL                     1170
#define IDC_EDIT_FR                     1171
#define IDC_EDIT_FC                     1172
#define IDC_EDIT_LFE                    1173
#define IDC_EDIT_SL                     1174
#define IDC_EDIT_SR                     1175
#define IDC_LIST_ENGINES                1180
#define IDC_EDIT_ENGINE_NAME            1181
#define IDC_EDIT_ENGINE_PATH            1182
#define IDC_BUTTON_ENGINES_BROWSE       1183
#define IDC_BUTTON_ENGINES_ADD          1184
#define IDC_BUTTON_ENGINES_REMOVE       1185
#define IDC_BUTTON_ENGINES_IMPORT       1186
#define IDC_BUTTON_ENGINES_EXPORT       1187
#define IDC_STATIC_TEXT_ENGINE_NAME     1188
#define IDC_STATIC_TEXT_ENGINE_PATH     1189
#define IDC_STATIC_GROUP_ENGINE         1190
#define IDC_STATIC_TEXT_APP_NAME        1200
#define IDC_STATIC_TEXT_WEBSITE         1201
#define IDC_STATIC_TEXT_EMAIL           1202
#define IDC_STATIC_LICENSE              1203
#define ID_FILE_ADDFILES                32771
#define ID_FILE_ADDDIRECTORY            32772
#define ID_FILE_MUXWIZARD               32773
#define ID_FILE_LOADFILESLIST           32774
#define ID_FILE_SAVEFILESLIST           32775
#define ID_FILE_LOADPRESETS             32776
#define ID_FILE_SAVEPRESETS             32777
#define ID_FILE_EXIT                    32778
#define ID_OPTIONS_DISABLEALLWARNINGS   32790
#define ID_OPTIONS_SAVEONEXIT           32791
#define ID_OPTIONS_SAVECONFIGURATION    32792
#define ID_OPTIONS_LOADCONFIGURATION    32793
#define ID_LANGUAGE_DEFAULT             32801
#define ID_HELP_WEBSITE                 32810
#define ID_HELP_ABOUT                   32811
#define ID_LIST_ADDFILES                32820
#define ID_LIST_ADDDIRECTORY            32821
#define ID_LIST_DELFILES                32822
#define ID_LIST_CLEARLIST               32823
#define ID_LIST_LOADLIST                32824
#define ID_LIST_SAVELIST                32825
#define ID_LIST_MOVEUP                  32826
#define ID_LIST_MOVEDOWN                32827
#define ID_LIST_MUXWIZARD               32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1210
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
