//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EncWAVtoAC3.rc
//
#define IDR_MAINFRAME                   102
#define IDD_ENCWAVTOAC3_DIALOG          128
#define IDD_ENCODING_DIALOG             129
#define IDR_MENU_MAIN                   130
#define IDD_ABOUT_DIALOG                131
#define IDB_ABOUT_BITMAP                132
#define IDR_MENU_LIST                   133
#define IDD_MUX_DIALOG                  134
#define IDD_ENGINES_DIALOG              135
#define IDC_PROGRESS_CURRENT            1001
#define IDC_PROGRESS_TOTAL              1002
#define IDC_LIST_FILES                  1003
#define IDC_BUTTON_ADD                  1004
#define IDC_BUTTON_ENCODE               1005
#define IDC_LIST_SETTINGS               1006
#define IDC_STATIC_IN_01                1007
#define IDC_BUTTON_MUX_WIZARD           1008
#define IDC_STATIC_OUT                  1009
#define IDC_STATIC_IN_INFO_01           1010
#define IDC_STATIC_ELAPSED_CURRENT      1011
#define IDC_SLIDER_BITRATE              1012
#define IDC_STATIC_ENCODER_LABEL        1013
#define IDC_STATIC_IN_00                1014
#define IDC_STATIC_OUT_INFO             1015
#define IDC_BUTTON_PRESETS_DEFAULTS     1016
#define IDC_STATIC_READS_LABEL          1017
#define IDC_STATIC_IN_INFO_00           1018
#define IDC_STATIC_ELAPSED_TOTAL        1019
#define IDC_CHECK_VBR                   1020
#define IDC_STATIC_WRITES_LABEL         1021
#define IDC_STATIC_IN_02                1022
#define IDC_STATIC_SIMD_INFO            1023
#define IDC_STATIC_LICENSE              1024
#define IDC_STATIC_IN_INFO_02           1025
#define IDC_STATIC_BITRATE              1026
#define IDC_STATIC_IN_03                1027
#define IDC_COMBO_SETTING               1028
#define IDC_STATIC_IN_INFO_03           1029
#define IDC_COMBO_PRESETS               1030
#define IDC_STATIC_ENCODER_UNIT         1031
#define IDC_STATIC_IN_04                1032
#define IDC_BUTTON_PRESET_ADD           1033
#define IDC_STATIC_READS_UNIT           1034
#define IDC_STATIC_IN_INFO_04           1035
#define IDC_BUTTON_PRESET_DEL           1036
#define IDC_STATIC_WRITES_UNIT          1037
#define IDC_STATIC_IN_05                1038
#define IDC_EDIT_OUTPUT_PATH            1039
#define IDC_STATIC_IN_INFO_05           1040
#define IDC_BUTTON_BROWSE               1041
#define IDC_STATIC_QUALITY              1042
#define IDC_STATIC_ENCODER_SPEED_AVG    1043
#define IDC_STATIC_OPTION_VALUE         1044
#define IDC_STATIC_READS_SPEED_AVG      1045
#define IDC_STATIC_THREADS              1046
#define IDC_STATIC_WRITES_SPEED_AVG     1047
#define IDC_STATIC_OUTPUT               1048
#define IDC_EDIT_THREADS                1049
#define IDC_SPIN_THREADS                1050
#define IDC_BUTTON_ENGINES              1051
#define IDC_CHECK_SIMD_MMX              1052
#define IDC_CHECK_SIMD_SSE              1053
#define IDC_CHECK_SIMD_SSE2             1054
#define IDC_CHECK_SIMD_SSE3             1055
#define IDC_STATIC_SAMPLE_FORMAT        1056
#define IDC_COMBO_RAW_SAMPLE_FORMAT     1057
#define IDC_STATIC_SAMPLE_RATE          1058
#define IDC_EDIT_RAW_SAMPLE_RATE        1059
#define IDC_SPIN_RAW_SAMPLE_RATE        1060
#define IDC_STATIC_CHANNELS             1061
#define IDC_EDIT_RAW_CHANNELS           1062
#define IDC_STATIC_FILES                1063
#define IDC_SPIN_RAW_CHANNELS           1064
#define IDC_STATIC_BUILD_INFO           1065
#define IDC_STATIC_ENGINE               1066
#define IDC_COMBO_ENGINES               1067
#define IDC_CHECK_MULTIPLE_MONO_INPUT   1068
#define IDC_STATIC_GROUP_ENCODING       1069
#define IDC_BUTTON_FL                   1070
#define IDC_STATIC_PRESET               1071
#define IDC_BUTTON_FR                   1072
#define IDC_STATIC_SIMD                 1073
#define IDC_BUTTON_FC                   1074
#define IDC_BUTTON_LFE                  1075
#define IDC_BUTTON_SL                   1076
#define IDC_BUTTON_SR                   1077
#define IDC_BUTTON_CLEAR_FL             1078
#define IDC_BUTTON_CLEAR_FC             1079
#define IDC_BUTTON_CLEAR_FR             1080
#define IDC_BUTTON_CLEAR_LFE            1081
#define IDC_BUTTON_CLEAR_SL             1082
#define IDC_BUTTON_CLEAR_SR             1083
#define IDC_BUTTON_S                    1084
#define IDC_STATIC_LABEL_FL             1085
#define IDC_STATIC_LABEL_FR             1086
#define IDC_STATIC_LABEL_FC             1087
#define IDC_STATIC_LABEL_LFE            1088
#define IDC_STATIC_LABEL_SL             1089
#define IDC_STATIC_LABEL_SR             1090
#define IDC_COMBO_CHANNEL_CONFIG        1091
#define IDC_CHECK_CHANNEL_CONFIG_LFE    1092
#define IDC_BUTTON_EXPORT               1093
#define IDC_BUTTON_IMPORT               1094
#define IDC_LIST_ENGINES                1095
#define IDC_EDIT_ENGINE_NAME            1096
#define IDC_EDIT_ENGINE_PATH            1097
#define IDC_BUTTON_ENGINES_REMOVE       1098
#define IDC_EDIT_FL                     1099
#define IDC_EDIT_FR                     1100
#define IDC_EDIT_FC                     1101
#define IDC_EDIT_LFE                    1102
#define IDC_EDIT_SL                     1103
#define IDC_EDIT_SR                     1104
#define IDC_STATIC_GROUP_STATS          1105
#define IDC_BUTTON_ENGINES_IMPORT       1106
#define IDC_BUTTON_ENGINES_EXPORT       1107
#define IDC_BUTTON_ENGINES_ADD          1108
#define IDC_BUTTON_ENGINES_BROWSE       1109
#define IDC_MFCBUTTON_ABOUT_BITMAP      1111
#define ID_LIST_ADDFILES                32771
#define ID_LIST_ADDDIRECTORY            32772
#define ID_LIST_DELFILES                32773
#define ID_LIST_CLEARLIST               32774
#define ID_LIST_LOADLIST                32775
#define ID_LIST_SAVELIST                32776
#define ID_FILE_EXIT                    32777
#define ID_HELP_WEBSITE                 32778
#define ID_HELP_ABOUT                   32779
#define ID_FILE_LOADPRESETS             32780
#define ID_FILE_SAVEPRESETS             32781
#define ID_FILE_LOADFILESLIST           32782
#define ID_FILE_SAVEFILESLIST           32783
#define ID_LIST_MOVEUP                  32784
#define ID_LIST_MOVEDOWN                32785
#define ID_HELP_COMMAND_LINE            32786
#define ID_FILE_ADDFILES                32788
#define ID_FILE_ADDDIRECTORY            32789
#define ID_FILE_MUXWIZARD               32790
#define ID_LIST_MUXWIZARD               32791
#define ID_OPTIONS_DISABLEALLWARNINGS   32792
#define ID_OPTIONS_SAVECONFIGURATIONONEXIT 32793
#define ID_OPTIONS_SAVECONFIGURATION    32794
#define ID_OPTIONS_LOADCONFIGURATION    32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
